# Generated by Django 3.0.4 on 2020-04-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='User uuid field')),
                ('cookie_id', models.CharField(max_length=256, verbose_name='User cookie ID')),
                ('browser_id', models.CharField(max_length=256, verbose_name='User brower ID')),
                ('device_id', models.CharField(max_length=256, verbose_name='User device ID')),
                ('submissions', models.IntegerField(verbose_name='User number of submissions')),
            ],
        ),
    ]
