# Generated by Django 3.0.5 on 2020-04-14 13:24

import beatcovid.respondent.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respondent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(default=beatcovid.respondent.models.default_expiry_date)),
                ('transfer_key', models.CharField(max_length=6, unique=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='respondent.Respondent')),
            ],
        ),
    ]
